### ISSUE TITLE
Python2 Compilation

### ISSUE THREAD

**Issue by jtliso** [bnaecker/pygsvd#1]
Do you know if there is an easy way to compile this in Python2 instead of Python3? I get C errors referring to the gsvdmodule struct in the C file beginning at line 185 when I try to compile with Python2 instead of 3.

I'd like to be able to use this in Python2 if possible because all of my current development is in Python2.

**Comment by jtliso** [comment]
Figured it out. For those seeing this in the future, you must use the following to define and initialize the module instead of PyModuleDef and PyMODINIT calls the author uses in src/_gsvd.c. 

```

PyMODINIT_FUNC init_gsvd(void){
        import_array();
        Py_InitModule3("_gsvd", GsvdMethods, "Compute the generalized singular value decomposition of two matrices.");
}
```

Also, you may need to change the type of the compute_uvq to integers instead of bools. I was having issues with that as well.

```
        const char arg_format[] = "O!O!O!O!O!O!O!O!iii";
```

**Comment by bnaecker** [comment]
Thanks @jtliso, I've updated the package to allow for building using both Python2 and Python3.
